//
//  CoreDataEnvir.h
//  CoreDataLab
//
//	CoreData enviroment.
//	Support CoreData operating methods.
//
//	Create record item.
//	Support concurrency operating.
//
//  Created by NicholasXu on 11-5-25.
//  Copyright 2011 NicholasXu. All rights reserved.
//


#import <UIKit/UIKit.h>
#import <CoreData/CoreData.h>

#define CORE_DATA_ENVIR_SHOW_LOG        0
/**
 Triggle to enable persistance shared.
 */
#define CORE_DATA_SHARE_PERSISTANCE     0

#pragma mark - ------------------------------ CoreDataEnvirObserver (Not be used temporarily) ---------------------------

@protocol CoreDataEnvirObserver

@optional
- (void)didFetchingFinished:(NSArray *) aItems;
- (void)didUpdateContext:(id)sender;
- (void)didDeleteObjects:(id)sender;
- (void)didInsertObjects:(id)sender;
- (void)didUpdateObjects:(id)sender;

@end

#pragma mark - ------------------------------ CoreDataEnvirement -----------------------

@interface CoreDataEnvir : NSObject <NSFetchedResultsControllerDelegate> {
	NSManagedObjectModel * model;
	NSManagedObjectContext * context;
	NSFetchedResultsController * fetchedResultsCtrl;
    NSRecursiveLock *recursiveLock;
}

/**
 A model object.
 */
@property (nonatomic, retain) NSManagedObjectModel	*model;

/**
 A context object.
 */
@property (nonatomic, readonly) NSManagedObjectContext *context;

#if !CORE_DATA_SHARE_PERSISTANCE
/**
 A persistance coordinator object.
 */
@property (nonatomic, retain) NSPersistentStoreCoordinator *storeCoordinator;
#endif

/**
 A NSFetchedResultsController object, not be used by now.
 */
@property (nonatomic, retain) NSFetchedResultsController * fetchedResultsCtrl;

/**
 Model file name. It normally be name.momd
 */
@property (nonatomic, copy, setter = registModelFileName:, getter = modelFileName) NSString *modelFileName;

/**
 Data base file name. It can be whatever you want.
 */
@property (nonatomic, copy, setter = registDatabaseFileName:, getter = databaseFileName) NSString *databaseFileName;

/*
 Regist the specific model file name.
 */
+ (void)registDefaultModelFileName:(NSString *)name;

/*
 Regist the specific database file name.
 */
+ (void)registDefaultDatabaseFileName:(NSString *)name;

/*
 Get model file name.(Name likes: xxxx.mmod in sandbox.)
 */
+ (NSString *)defaultModelFileName;

/*
 Get data base file name.
 */
+ (NSString *)defaultDatabaseFileName;

/*
 Creating instance conditionally.
 If current thread is main thread return single main instance,else return an temporary new instance.
 */
+ (CoreDataEnvir *)instance;

/**
 Create an CoreDataEnvir instance by specified db file name and momd file name.
 The momd file name is a middle file generated by XCode handle xcdatamodeld file.
 
 @param databaseFileName    A specified db file name.
 @param modelFileName       A specified momd file name.
 */
+ (CoreDataEnvir *)createInstanceWithDatabaseFileName:(NSString *)databaseFileName modelFileName:(NSString *)modelFileName;

/*
 Only returen a single instance runs on main thread.
 */
+ (CoreDataEnvir *)mainInstance;

/*
 Creating a new instance.
 */
+ (CoreDataEnvir *)createInstance;

/*
 Release the main instance.
 */
//+ (void)deleteInstance;

/**
 Return data root path
 */
+ (NSString *)dataRootPath;

/*
 Operating on NSManagedObject
 */
- (id)dataItemWithID:(NSManagedObjectID *)objectId;
- (id)updateDataItem:(NSManagedObject *)object;
- (BOOL)deleteDataItem:(NSManagedObject *)aItem;
- (BOOL)deleteDataItemSet:(NSSet *)aItemSet;
- (BOOL)deleteDataItems:(NSArray*)items;
- (BOOL)saveDataBase;

@end

#pragma mark -  NSObject (Debug_Ext)

/*
 NSObject (Debug_Ext)
 */
@interface NSObject (Debug_Ext)

- (NSString *)currentDispatchQueueLabel;

@end

#pragma mark - NSmanagedObject convinent methods.

@interface NSManagedObject (CONVENIENT)

#pragma mark - Operation on main thread.
/*
 Creating managed object on main thread.
 */
+ (id)insertItem;
+ (id)insertItemWithBlock:(void(^)(id item))settingBlock;

/*
 Just fetching record items by the predicate on main thread.
 */
+ (NSArray *)items;
+ (NSArray *)itemsWithPredicate:(NSPredicate *)predicate;
+ (id)lastItem;
+ (id)lastItemWithPredicate:(NSPredicate *)predicate;

/*
 Remove item.
 */
- (void)remove;

/*
 Save db on main thread.
 */
- (BOOL)save;


#pragma mark - Operation on other sperate thread.

/*
 Creating managed object on background thread.
 */
+ (id)insertItemInContext:(CoreDataEnvir *)cde;
+ (id)insertItemInContext:(CoreDataEnvir *)cde fillData:(void (^)(id item))settingBlock;

/*
 Fetching record items by the predicate on background thread.
 */
+ (NSArray *)itemsInContext:(CoreDataEnvir *)cde;
+ (NSArray *)itemsInContext:(CoreDataEnvir *)cde usingPredicate:(NSPredicate *)predicate;
+ (id)lastItemInContext:(CoreDataEnvir *)cde;
+ (id)lastItemInContext:(CoreDataEnvir *)cde usingPredicate:(NSPredicate *)predicate;

- (id)update;
- (id)updateInContext:(CoreDataEnvir *)cde;

/*
 Remove item.
 */
- (void)removeFrom:(CoreDataEnvir *)cde;

/*
 Save db on main thread.
 */
- (BOOL)saveTo:(CoreDataEnvir *)cde;

@end



